[Style]
WindowRounding = 5
ScrollbarSize = 12
ScrollbarRounding = 2
FramePadding = [ 8, 5 ]

[Colors]
# rosewater: #f2d5cf
# flamingo: #eebebe
# pink: #f4b8e4
# mauve: #ca9ee6
# red: #e78284
# maroon: #ea999c
# peach: #ef9f76

# yellow: #e5c890
CheckMark = "#e5c890"
SliderGrab = "#e5c890"
SliderGrabActive = "#e5c890"
SeparatorHovered = "#e5c890"
SeparatorActive = "#e5c890"
ResizeGripHovered = "#e5c890a7"
ResizeGripActive = "#e5c890ed"
TabHovered = "#e5c8903f"
TabActive = "#e5c8903f"
PlotLines = "#e5c8907f"
PlotLinesHovered = "#e5c890"
PlotHistogram = "#e5c8907f"
PlotHistogramHovered = "#e5c890"
TableBorderStrong = "#e5c89010"
TableBorderLight = "#e5c89009"
TextSelectedBg = "#e5c8901f"

# green: #a6d189
# teal: #81c8be
# sky: #99d1db
# sapphire: #85c1dc
# blue: #8caaee
# lavender: #babbf1

# text: #c6d0f5
Text = "#c6d0f5"

# subtext1: #b5bfe2

# subtext0: #a5adce
TextDisabled = "#a5adce"

# overlay2: #949cbb

# overlay1: #838ba7
ScrollbarGrabActive = "#838ba7"

# overlay0: #737994
ScrollbarGrabHovered = "#737994"

# surface2: #626880
ScrollbarGrab = "#626880"

# surface1: #51576d
ButtonHovered = "#51576d"
Separator = "#51576d"

# surface0: #414559
TitleBg = "#414559"
TitleBgActive = "#414559"
FrameBgActive = "#414559"
Button = "#414559"
HeaderHovered = "#414559"
Tab = "#414559"

# base: #303446
WindowBg = "#303446fe"
PopupBg = "#303446fe"

# mantle: #292c3c
Border = "#292c3c"
FrameBgHovered = "#292c3c"
ButtonActive = "#292c3c"
Header = "#292c3c"
MenuBarBg = "#292c3c"
TableRowBgAlt = "#292c3cfa"

# crust: #232634
FrameBg = "#232634"
HeaderActive = "#232634"
